export const newsData = [
  {
    id: 1,
    title: "Global Summit 2026: Leaders Agree on New Climate Action Plan",
    slug: "global-climate-summit-2026",
    excerpt: "World leaders have signed a historic pact to reduce carbon emissions by 50% within the next decade.",
    content: "Full article content goes here...",
    category: "International",
    image: "https://img.freepik.com/premium-photo/online-news-mobile-phone-close-up-businesswoman-reading-news-articles-smartphone-screen-application-hand-holding-smart-device-mockup-website-newspaper-portal-internet_157125-9553.jpg?semt=ais_hybrid&w=740&q=80",
    author: "John Doe",
    date: "Jan 06, 2026",
    isFeatured: true,
  },
  {
    id: 2,
    title: "National Cricket Team Announces New Squad for World Cup",
    slug: "national-cricket-squad-announced",
    excerpt: "Unexpected changes in the lineup as veteran players retire.",
    content: "Full article content goes here...",
    category: "Sports",
    image: "https://media.gettyimages.com/id/942206186/photo/sports-balls-on-the-field-with-yard-line-soccer-ball-american-football-and-baseball-in-yellow.jpg?s=612x612&w=0&k=20&c=L9rb9ctlbYo6TVmqr-Vzz8qBWF19MIZDGeMz9TeyUdU=",
    author: "Sarah Smith",
    date: "Jan 05, 2026",
    isTrending: true,
  },
  {
    id: 3,
    title: "Tech Giant Unveils Quantum Smartphone Prototype",
    slug: "tech-giant-quantum-smartphone",
    excerpt: "The new device promises processing speeds 100x faster than current models.",
    content: "Full article content goes here...",
    category: "Technology",
    image: "https://img.freepik.com/premium-photo/online-news-mobile-phone-close-up-businesswoman-reading-news-articles-smartphone-screen-application-hand-holding-smart-device-mockup-website-newspaper-portal-internet_157125-9553.jpg?semt=ais_hybrid&w=740&q=80",
    author: "Mike Chen",
    date: "Jan 06, 2026",
    isFeatured: true,
  },
  {
    id: 4,
    title: "Stock Markets Hit Record Highs Amid Economic Boom",
    slug: "stock-markets-record-highs-2026",
    excerpt: "Investors celebrate as major indices surpass all-time expectations.",
    content: "Full article content goes here...",
    category: "National",
    image: "https://media.gettyimages.com/id/1739364307/photo/london-england-hundreds-attend-a-protest-called-by-the-national-jewish-assembly-the-camapaign.jpg?s=612x612&w=0&k=20&c=OrQrhSP_V2rGZ-wx_Dn4tx7LOq0_QF5d96UizufJlCk=",
    author: "Emily Blunt",
    date: "Jan 04, 2026",
    isTrending: false,
  },
  {
    id: 5,
    title: "New Mars Colony Project Accepts First Applicants",
    slug: "mars-colony-applicants-2026",
    excerpt: "SpaceX and NASA joint venture opens doors for civilian pioneers.",
    content: "Full article content goes here...",
    category: "Technology",
    image: "https://www.gstatic.com/bricks/image/7J5Ts_CtMytzsKb0EkIXsVBteL1mKyzY7b3Ikoz_1SATNzWspReAsJRKMRrlnYKqle6VI_VEcIs.png",
    author: "David Bowie",
    date: "Jan 03, 2026",
    isFeatured: false,
  },
  {
    id: 6,
    title: "Local Art Festival Draws Thousands to City Center",
    slug: "local-art-festival-2026",
    excerpt: "A celebration of culture, music, and street art revitalizes downtown.",
    content: "Full article content goes here...",
    category: "Entertainment",
    image: "https://media.gettyimages.com/id/638651186/photo/festival-selfie.jpg?s=612x612&w=0&k=20&c=0VGMexp7GoCK_OshclIbPz7r01Lu93O6Y0kq6zQ43Xc=",
    author: "Alice Cooper",
    date: "Jan 02, 2026",
    isTrending: true,
  },
  {
    id: 7,
    title: "Breakthrough in Alzheimer's Research Announced",
    slug: "alzheimers-research-breakthrough",
    excerpt: "Scientists identify a new protein marker that could lead to early detection.",
    content: "Full article content goes here...",
    category: "Technology",
    image: "https://img.freepik.com/premium-photo/online-news-mobile-phone-close-up-businesswoman-reading-news-articles-smartphone-screen-application-hand-holding-smart-device-mockup-website-newspaper-portal-internet_157125-9553.jpg?semt=ais_hybrid&w=740&q=80",
    author: "Dr. House",
    date: "Jan 06, 2026",
    isFeatured: true,
  },
  {
    id: 8,
    title: "Electric Vehicle Sales Surpass Gas Cars for First Time",
    slug: "ev-sales-surpass-gas-2026",
    excerpt: "A historic shift in the automotive industry as green energy takes the lead.",
    content: "Full article content goes here...",
    category: "Technology",
    image: "https://media.gettyimages.com/id/1187179171/photo/futuristic-office.jpg?s=612x612&w=0&k=20&c=GbJoBwiAVklbGLD0rkk67xyYBk_cuoSP-D-ujEHGLdo=",
    author: "Elon T.",
    date: "Jan 01, 2026",
    isTrending: false,
  },
  {
    id: 9,
    title: "Education Reform Bill Passes in Parliament",
    slug: "education-reform-bill-passes",
    excerpt: "New legislation mandates coding classes for all primary school students.",
    content: "Full article content goes here...",
    category: "National",
    image: "https://media.gettyimages.com/id/1241769423/photo/tokyo-japan-people-read-a-special-edition-of-a-japanese-national-newspaper-which-was.jpg?s=612x612&w=0&k=20&c=xpKUZRfPjj45f2SNL0Z0eAxytOpKSELNmo5D2gLaHrE=",
    author: "Leslie Knope",
    date: "Jan 05, 2026",
    isFeatured: false,
  },
  {
    id: 10,
    title: "Award-Winning Director Teases Upcoming Sci-Fi Trilogy",
    slug: "director-teases-scifi-trilogy",
    excerpt: "Fans go wild as the teaser trailer drops for the highly anticipated series.",
    content: "Full article content goes here...",
    category: "Entertainment",
    image: "https://media.gettyimages.com/id/497317250/photo/new-year-party.jpg?s=612x612&w=0&k=20&c=ssF8Nl4srRSnNhToYI0GlUznz3xVVJunOnaIe1ukllA=",
    author: "Steven S.",
    date: "Jan 04, 2026",
    isTrending: true,
  },
  {
    id: 11,
    title: "Cybersecurity Alert: New AI Phishing Scam Detected",
    slug: "ai-phishing-scam-alert",
    excerpt: "Experts warn of hyper-realistic voice cloning used in banking fraud.",
    content: "Full article content goes here...",
    category: "Technology",
    image: "https://static.vecteezy.com/system/resources/thumbnails/040/979/279/small/ai-generated-senior-experiencing-vr-technology-photo.jpg",
    author: "Kevin Mitnick",
    date: "Jan 06, 2026",
    isFeatured: false,
  },
  {
    id: 12,
    title: "Sustainable Fashion Week Kicks Off in Paris",
    slug: "sustainable-fashion-week-paris",
    excerpt: "Top designers showcase collections made entirely from recycled materials.",
    content: "Full article content goes here...",
    category: "International",
    image: "https://img.freepik.com/premium-photo/online-news-mobile-phone-close-up-businesswoman-reading-news-articles-smartphone-screen-application-hand-holding-smart-device-mockup-website-newspaper-portal-internet_157125-9553.jpg?semt=ais_hybrid&w=740&q=80",
    author: "Coco C.",
    date: "Jan 03, 2026",
    isTrending: true,
  },
  {
    id: 13,
    title: "Heavy Snowfall Disrupts Travel in Northern Hemisphere",
    slug: "snowfall-travel-disruption-2026",
    excerpt: "Airports and highways closed as winter storm 'Titan' hits hard.",
    content: "Full article content goes here...",
    category: "International",
    image: "https://static.toiimg.com/thumb/imgsize-1156461,msid-126355391,width-600,resizemode-4/126355391.jpg",
    author: "Storm Chaser",
    date: "Jan 02, 2026",
    isFeatured: false,
  },
  {
    id: 14,
    title: "Startup Raises $50M for Lab-Grown Coffee",
    slug: "startup-lab-grown-coffee",
    excerpt: "The future of caffeine is here, promising sustainability without the beans.",
    content: "Full article content goes here...",
    category: "Technology",
    image: "https://thumbs.dreamstime.com/b/information-technology-8229594.jpg",
    author: "Howard S.",
    date: "Jan 05, 2026",
    isTrending: false,
  },
  {
    id: 15,
    title: "Ancient Ruins Discovered Under Metropolis",
    slug: "ancient-ruins-under-metropolis",
    excerpt: "Construction workers stumble upon a 2,000-year-old underground city.",
    content: "Full article content goes here...",
    category: "National",
    image: "https://www.ctvnews.ca/resizer/v2/OLTG4EEX7ZGM5CU3HVVUJKAAOA.jpg?smart=true&auth=cf1719dbd04c3f5590fc2a78f31f4b1a245434967c3c7c2f66ece9a971446a01&width=600&height=337",
    author: "Indy Jones",
    date: "Jan 01, 2026",
    isFeatured: true,
  },
  {
    id: 16,
    title: "Virtual Reality Concerts Become the New Normal",
    slug: "vr-concerts-new-normal",
    excerpt: "Millions attend live shows from the comfort of their living rooms.",
    content: "Full article content goes here...",
    category: "Entertainment",
    image: "https://img.freepik.com/free-photo/hand-holding-entertainment-objects-isolated_53876-138341.jpg?semt=ais_hybrid&w=740&q=80",
    author: "Daft P.",
    date: "Jan 04, 2026",
    isTrending: true,
  },
  {
    id: 17,
    title: "Olympic Gold Medalist Announces Retirement",
    slug: "olympic-medalist-retires",
    excerpt: "The track and field legend bids farewell after a 15-year career.",
    content: "Full article content goes here...",
    category: "Sports",
    image: "https://t3.ftcdn.net/jpg/03/62/64/06/360_F_362640676_OzPaJsXZYvfo20FXAApkCUkRJI4tN6Sb.jpg",
    author: "Usain B.",
    date: "Jan 03, 2026",
    isFeatured: false,
  },
  {
    id: 18,
    title: "Space Hotel Orbital 1 Opens for Reservations",
    slug: "space-hotel-orbital-1",
    excerpt: "Luxury accommodation in low earth orbit is now a reality for the wealthy.",
    content: "Full article content goes here...",
    category: "International",
    image: "https://static.toiimg.com/thumb/imgsize-123456,msid-126339150,width-600,resizemode-4/126339150.jpg",
    author: "Richard B.",
    date: "Jan 06, 2026",
    isTrending: true,
  },
  {
    id: 19,
    title: "Championship Final: Underdogs Take the Trophy",
    slug: "championship-final-underdogs-win",
    excerpt: "In a stunning upset, the city's beloved team wins the league final.",
    content: "Full article content goes here...",
    category: "Sports",
    image: "https://i.pinimg.com/originals/0e/ca/e4/0ecae48201b9f920125dcfe4ea10a086.jpg",
    author: "Ted Lasso",
    date: "Jan 05, 2026",
    isFeatured: true,
  },
  {
    id: 20,
    title: "Govt Launches Digital Currency Pilot Program",
    slug: "govt-digital-currency-pilot",
    excerpt: "Central bank tests digital wallet system for public welfare distribution.",
    content: "Full article content goes here...",
    category: "National",
    image: "https://media.gettyimages.com/id/2161948008/photo/abc-news-signage-during-the-republican-national-convention-at-the-fiserv-forum-in-milwaukee.jpg?s=612x612&w=0&k=20&c=fMIzy_bLpNV-biPBuPig7Dk7IAAERphZSQdjQbsvN_g=",
    author: "Satoshi N.",
    date: "Jan 02, 2026",
    isTrending: false,
  },
];

// Tried to do like database fetch
export async function getNews() {
  return newsData;
}

export async function getNewsById(id) {
  return newsData.find((item) => item.id === parseInt(id));
}

export async function getNewsByCategory(categorySlug) {
  return newsData.filter(item => 
    item.category.toLowerCase() === categorySlug.toLowerCase()
  );
}
